###############################################################################
# File Name: assignment_02a.py
#
# Description: This Python program defines an nflModel class that scrapes NFL 
# team stats from a webpage, preprocesses the data, stores it in a SQLite 
# database, trains a logistic regression model to predict whether a team has 
# a winning record, tests the model on new data, and saves the trained model 
# for future use.
# 
# Note: Cookie header removed; original cookie was session-specific and 
# automatically generated by Postman during testing.
#
# Record of Revisions (Date | Author | Change):
# 08/27/2025 | Rhys DeLoach | Initial creation
###############################################################################

# Import Libraries
import pandas as pd
import numpy as np
import sqlite3 as sql
import requests
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

class nflModel:
    def __init__(self):
        pass
    
    def getData(self):  
        url = "https://www.pro-football-reference.com/years/2023/"

        payload = {}
        headers = {
        'Cookie': 'REMOVED'
        }

        response = requests.request("GET", url, headers=headers, data=payload)

        html = pd.read_html(response.text) # Read all tables in the webpage

        nflData = pd.concat([html[0], html[1]], ignore_index=True) # Combine the two tables
        return nflData
    
    def preprocessData(self, nflData):
        nflData = nflData[~nflData['Tm'].str.contains('AFC|NFC')].copy() # Remove conference rows

        statsCols = ['PF', 'PA', 'PD','SoS'] # Stats to be used for prediction
        nflData[statsCols] = nflData[statsCols].apply(pd.to_numeric) # Convert to numeric

        nflData = nflData.drop(columns=['W-L%']) # Drop W-L% column

        nflData['winningRecord'] = nflData.apply(lambda x: 1 if int(x['W']) > int(x['L']) else 0, axis = 1) # Create winningRecord column

        nflData = nflData[statsCols + ['winningRecord']] # Keep only relevant columns
        return nflData

    def toSQL(self, nflData):
        conn = sql.connect('data/NFL.db') # Create database
        nflData.to_sql('stats', conn, if_exists='replace', index = False) # Write data to SQL table
        conn.close() # Close connection

    def pullSql(self):
        conn = sql.connect('data/NFL.db') # Connect to database
        X = pd.read_sql_query("SELECT PF, PA, PD, SoS FROM stats", conn) # Features
        y = pd.read_sql_query("SELECT winningRecord FROM stats", conn).squeeze() # Target
        conn.close() # Close connection
        return X, y
    
    def trainModel(self, X, y):
        X_train,_,y_train,_ = train_test_split(X,y,test_size=0.2,random_state=42) # Split data
        logReg = LogisticRegression() # Create model
        logReg.fit(X_train,y_train) # Train model
        return logReg

    def saveModel(self,model):
        joblib.dump(model, 'output/nflModel.joblib') # Save model

    def testModel(self, model):
        testData = pd.DataFrame({'PF':[465],'PA':[380],'PD':[85],'SoS':[1.5]}) # Test data for Atlanta Vipers
        prediction = model.predict(testData) # Make prediction
        print(f'The Atlanta Vipers had a {"winning" if prediction == 1 else "losing"} record') # Print result

        testData['winningRecord'] = prediction # Add prediction to test data

        conn = sql.connect('data/NFL.db') # Connect to database
        testData.to_sql('stats', conn, if_exists='append', index = False) # Append test data to SQL table
        conn.close() # Close connection

if __name__ == "__main__":
    nfl = nflModel()
    data = nfl.getData()
    processedData = nfl.preprocessData(data)
    nfl.toSQL(processedData)
    X, y = nfl.pullSql()
    model = nfl.trainModel(X, y)
    nfl.testModel(model)
    nfl.saveModel(model)